Update delivery on detail change
linn/purchasing pull request #427
Opened 2022-10-25 15:53 UTC by RossStewart

C# changes. Question is now do we remove recalculateDetailFields from the purchaseorder reducer? Going to submit that as a separate PR if consensus is yes

2022-10-26 07:10 UTC, richardiphillips commented
> C# changes. Question is now do we remove recalculateDetailFields from the purchaseorder reducer? Going to submit that as a separate PR if consensus is yes

why would we remove it?

2022-10-26 07:33 UTC, lewisrenfrew requested changes
Looks like you've misunderstood the issue here - you need to update prices on all outstanding deliveries to be the new prices entered by the user

2022-10-26 07:33 UTC, lewisrenfrew commented on src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
> +                    var updatedDelivery = updatedDeliveries.First(x => x.DeliverySeq == delivery.DeliverySeq);
If I'm reading this right it looks like you are just setting all the prices based off of what the delivery price used to be. How is that going to keep them in sync with any changes to the prices on the order detail?

2022-10-26 07:33 UTC, lewisrenfrew commented on src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
> +                }
How are you calculating VAT etc?

2022-10-26 07:33 UTC, lewisrenfrew commented on tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs
> +                                                                           BaseDeliveryTotal = 0m,
why set all these to 0?

2022-10-26 07:33 UTC, lewisrenfrew commented on tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs
> +            delivery.OrderUnitPriceCurrency.Should().Be(120m);
You didn't change this away from 120m in these tests so this isn't testing the delivery price was updated

2022-10-26 07:33 UTC, lewisrenfrew commented on tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderOverrideValueQtyFields.cs
> +            delivery.OrderUnitPriceCurrency.Should().Be(120m);
this test updated this to be 200.22 on the detail - Why are you testing that its 120 here?

2022-10-27 13:09 UTC, lewisrenfrew approved these changes
looks good - Should work out / ask Andy & co what should happen when they change the qty next. presumably the deliveries will need updated in that case too.

(merge this first of course)

2022-10-27 13:14 UTC, merged

2022-10-27 13:15 UTC, RossStewart commented
> looks good - Should work out / ask Andy & co what should happen when they change the qty next. presumably the deliveries will need updated in that case too.
> 
> (merge this first of course)

Looks like Andy is on holiday until the 31st, should I maybe ask Scott or Mandy? Will look into that issue we spoke about on stand up for the moment (Andrew is giving me details) and then see what the next move is